name: aesthetic_weather_app
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0' # (Your SDK version might be slightly different, that's okay)

# --- THIS IS THE IMPORTANT SECTION ---
# Make sure you only have ONE dependencies: block
dependencies:
  flutter:
    sdk: flutter

  # Your app's packages
  cupertino_icons: ^1.0.2
  http: ^1.2.1               # (Your version might be ^1.5.0, that's fine)
  geolocator: ^14.0.2
  geocoding: ^4.0.0
  lottie: ^3.1.2               # (Your version might be ^3.3.2, that's fine)

# --- And one dev_dependencies: block ---
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0      # (Your version might be ^5.0.0, that's fine)

# --- And the flutter: block ---
flutter:
  uses-material-design: true

  # Make sure this section is correct
  assets:
    - assets/